# Generated by Django 5.0.2 on 2024-10-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('handle', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('biometrics', models.CharField(max_length=255)),
                ('public_private_key_pair', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHealthRecords',
            fields=[
                ('share_health_records_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_records_info', models.JSONField()),
                ('access_link', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='SharedInfo',
            fields=[
                ('shared_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=255)),
                ('info_field', models.CharField(max_length=100)),
                ('verification_token', models.CharField(max_length=255)),
                ('shared_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='PublicProfiles',
            fields=[
                ('public_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_info', models.JSONField()),
                ('visibility', models.BooleanField(default=True)),
                ('public_profile_link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegeRings',
            fields=[
                ('ring_id', models.AutoField(primary_key=True, serialize=False)),
                ('ring_name', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=50)),
                ('assigned_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=100)),
                ('record_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ExportLogs',
            fields=[
                ('export_id', models.AutoField(primary_key=True, serialize=False)),
                ('export_format', models.CharField(max_length=50)),
                ('export_time', models.DateTimeField(auto_now_add=True)),
                ('exported_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('responder_id', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('trusted_contacts', models.JSONField()),
                ('emergency_info', models.JSONField()),
                ('criteria', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.AutoField(primary_key=True, serialize=False)),
                ('credential_type', models.CharField(max_length=100)),
                ('credential_image', models.JSONField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
